/* Агата Мебель — каталог работ.
   type: kitchen | wardrobe | kids | bath | living | stone (может быть несколько)
   style: classic | neo | modern | minimal
   photos: имена файлов из assets/img без расширения */
window.AGATA_TYPES = {
  kitchen:  'Кухни',
  wardrobe: 'Шкафы и гардеробные',
  kids:     'Детские',
  bath:     'Ванные',
  living:   'Гостиные и прихожие',
  stone:    'Камень'
};
window.AGATA_STYLES = {
  classic: 'Классика',
  neo:     'Неоклассика',
  modern:  'Современная',
  minimal: 'Минимализм'
};
window.PHOTO_DIMS = {"k-attic-1":[960,1280],"k-attic-2":[960,1280],"bath-mauve-1":[564,1280],"bath-mauve-2":[564,1280],"bath-mauve-3":[574,1256],"bath-marble-1":[960,1280],"k-paris-1":[720,1280],"bath-paris-1":[720,1280],"ward-classic-0":[590,916],"k-green-1":[1280,892],"k-white-1":[960,1190],"k-white-2":[960,1190],"k-white-3":[1059,1280],"k-oak-1":[1280,852],"k-oak-2":[1280,852],"k-peninsula-1":[960,1280],"k-peninsula-2":[960,1280],"hall-wood-1":[960,1280],"k-oakblack-1":[960,1280],"bath-grey-1":[960,1280],"ward-grey-1":[960,1280],"k-blue-1":[960,1190],"k-blue-2":[960,1280],"k-blue-3":[960,1280],"k-blue-4":[960,1280],"ward-classic-1":[720,1280],"ward-classic-2":[720,1280],"ward-classic-3":[720,1280],"kids-desk-1":[960,1280],"ward-classic-4":[720,1280],"kids-desk-2":[960,1280],"k-paris-2":[720,1280],"kids-room-1":[1040,780],"kids-room-2":[1040,780],"k-graphite-1":[960,1280],"k-graphite-2":[960,1280],"k-graphite-3":[960,1280],"k-taupe-1":[960,1280],"k-taupe-2":[960,1280],"k-taupe-3":[960,1280],"k-taupe-4":[960,1280],"k-grey-1":[1280,960],"bath-beige-1":[960,1280],"bath-beige-2":[960,1280],"k-loft-1":[1280,960],"bath-wood-1":[1024,768],"tv-marble-1":[960,1280],"k-stone-1":[1280,960],"bath-black-1":[960,1280],"k-cream-1":[960,1280],"bath-black-2":[1024,1280],"ward-white-1":[960,1280],"ward-glass-1":[1280,960],"ward-glass-2":[1280,960],"k-bar-1":[959,1280],"k-bar-2":[959,1280],"k-creamwood-1":[1264,848],"hall-cream-1":[1152,928],"k-woodclassic-1":[839,557],"min-1":[960,1190],"min-2":[1280,892],"min-3":[960,1190],"min-4":[1280,892],"min-5":[960,1190],"min-6":[1280,892],"min-7":[960,1190],"min-8":[1280,892],"min-9":[960,1190],"min-10":[720,1280],"min-11":[720,1280],"min-12":[720,1280],"min-13":[720,1280],"min-14":[720,1280]};
window.WORKS = [
  { id:'taupe',    title:'Кухня в тауповом глянце с латунью', type:['kitchen'], style:'neo',
    text:'Рифлёные вставки, витрины с подсветкой и латунный профиль по всему периметру. Столешница и фартук — под мрамор.',
    photos:['k-taupe-1','k-taupe-2','k-taupe-3','k-taupe-4'] },
  { id:'grey',     title:'Серая глянцевая кухня с витриной', type:['kitchen'], style:'modern',
    text:'Фасады в пол, пенал-витрина с подсветкой, фартук из дерева. Линия света вдоль столешницы.',
    photos:['k-grey-1'] },
  { id:'attic',    title:'Кухня в мансарде с островом', type:['kitchen'], style:'neo',
    text:'Матовые бежевые фасады до скоса крыши, остров с барной стойкой, вытяжка в форме камина.',
    photos:['k-attic-2','k-attic-1'] },
  { id:'cream',    title:'Кремовая кухня с патиной', type:['kitchen'], style:'classic',
    text:'Фасады с золотой патиной, пилястры, витрины, мраморный пол.',
    photos:['k-cream-1'] },
  { id:'bath-marble', title:'Ванная с двумя раковинами', type:['bath','stone'], style:'classic',
    text:'Подвесная тумба с латунными ручками, столешница из камня, зеркала в нишах.',
    photos:['bath-marble-1'] },
  { id:'paris',    title:'Кухня в парижской классике', type:['kitchen'], style:'classic',
    text:'Белые фасады с фрезеровкой, лепной декор на стенах, стол из слэба.',
    photos:['k-paris-1','k-paris-2'] },
  { id:'bath-paris', title:'Ванная с лепниной', type:['bath'], style:'classic',
    text:'Белая тумба под раковину, встроенные ниши, зеркало с подсветкой.',
    photos:['bath-paris-1'] },
  { id:'blue',     title:'Синяя кухня в неоклассике', type:['kitchen'], style:'neo',
    text:'Фасады с фрезеровкой, витрины, купол вытяжки, хрустальная люстра.',
    photos:['k-blue-2','k-blue-1','k-blue-4','k-blue-3'] },
  { id:'ward-classic', title:'Шкафы с лепным декором', type:['wardrobe'], style:'classic',
    text:'Белые распашные шкафы с резными накладками и вставкой из чёрного стекла.',
    photos:['ward-classic-1','ward-classic-3','ward-classic-2','ward-classic-4','ward-classic-0'] },
  { id:'kids-desk', title:'Детская с письменным столом', type:['kids'], style:'classic',
    text:'Белый стол с рифлёным фасадом на латунных ножках, навесной шкаф и витрина для коллекции.',
    photos:['kids-desk-2','kids-desk-1'] },
  { id:'kids-room', title:'Детская с домиком-стеллажом', type:['kids'], style:'modern',
    text:'Шкафы до потолка, стеллаж-домик, рабочее место у окна, ящики для игрушек.',
    photos:['kids-room-1','kids-room-2'] },
  { id:'min',      title:'Апартаменты в минимализме', type:['kitchen','wardrobe','living'], style:'minimal',
    text:'Мебель из ореха с округлыми углами, кремовая кухня со скульптурной столешницей, изголовье кровати, встроенные шкафы и панели в коридоре.',
    photos:['min-10','min-1','min-6','min-4','min-2','min-3','min-5','min-7','min-8','min-9','min-11','min-12','min-13','min-14'],
    video:'walk' },
  { id:'green',    title:'Зелёная кухня с островом', type:['kitchen'], style:'modern',
    text:'Матовые тёмно-зелёные фасады, белый верх, остров с барной стойкой.',
    photos:['k-green-1'] },
  { id:'white',    title:'Белая кухня до потолка', type:['kitchen'], style:'modern',
    text:'Гладкие фасады без ручек, встроенный холодильник, стол из керамики.',
    photos:['k-white-1','k-white-2','k-white-3'] },
  { id:'graphite', title:'Графитовая кухня', type:['kitchen'], style:'modern',
    text:'Матовые тёмно-серые фасады, мраморный фартук, чёрная техника.',
    photos:['k-graphite-1','k-graphite-2','k-graphite-3'] },
  { id:'oak',      title:'Кухня с фасадами цвета охры', type:['kitchen'], style:'modern',
    text:'Верхние шкафы цвета охры, открытые полки со стеклом, обеденная группа на латунных ножках.',
    photos:['k-oak-1','k-oak-2'] },
  { id:'bar',      title:'Кухня с барной стойкой', type:['kitchen'], style:'modern',
    text:'Белые фасады, витрина с подсветкой, барная стойка из дерева.',
    photos:['k-bar-1','k-bar-2'] },
  { id:'peninsula', title:'Кухня с полуостровом', type:['kitchen'], style:'modern',
    text:'Белые фасады, столешница из дерева, полуостров вместо обеденного стола.',
    photos:['k-peninsula-1','k-peninsula-2'] },
  { id:'oakblack', title:'Кухня дуб и чёрный мрамор', type:['kitchen','stone'], style:'modern',
    text:'Фасады из дуба, столешница и фартук из чёрного камня, серые нижние модули.',
    photos:['k-oakblack-1'] },
  { id:'stone',    title:'Кухня с каменным островом', type:['kitchen','stone'], style:'modern',
    text:'Фасады под камень, остров со столешницей из тёмного гранита, стеклянные подвесы.',
    photos:['k-stone-1'] },
  { id:'tv-marble', title:'ТВ-зона с мрамором', type:['living','stone'], style:'modern',
    text:'Портал из тёмного мрамора, полки из дерева с подсветкой, камин.',
    photos:['tv-marble-1'] },
  { id:'loft',     title:'Кухня в стиле лофт', type:['kitchen'], style:'modern',
    text:'Графитовые фасады, кирпичный фартук, остров с чёрной столешницей.',
    photos:['k-loft-1'] },
  { id:'creamwood', title:'Кремовая кухня с деревом', type:['kitchen'], style:'modern',
    text:'Матовые кремовые фасады, шкафы из шпона, витрина с подсветкой, мраморный фартук.',
    photos:['k-creamwood-1'] },
  { id:'woodclassic', title:'Кухня с рифлёными фасадами', type:['kitchen'], style:'neo',
    text:'Дерево и латунь, купол вытяжки, витрины с подсветкой.',
    photos:['k-woodclassic-1'] },
  { id:'hall-wood', title:'Прихожая с деревянными панелями', type:['living','wardrobe'], style:'modern',
    text:'Шкаф до потолка, открытая вешалка, панели из шпона с чёрными вставками.',
    photos:['hall-wood-1'] },
  { id:'hall-cream', title:'Прихожая со стеклянной витриной', type:['living','wardrobe'], style:'modern',
    text:'Шкаф с зеркалом, витрина, панели из шпона, банкетка.',
    photos:['hall-cream-1'] },
  { id:'ward-grey', title:'Шкаф с нишей и подсветкой', type:['wardrobe'], style:'modern',
    text:'Серые матовые фасады, открытая ниша из дерева с линейным светом.',
    photos:['ward-grey-1'] },
  { id:'ward-glass', title:'Гардеробная со стеклянными дверями', type:['wardrobe'], style:'classic',
    text:'Двери из матового стекла в пол, встроены в нишу.',
    photos:['ward-glass-1','ward-glass-2'] },
  { id:'ward-white', title:'Шкаф-купе с зеркалом', type:['wardrobe','living'], style:'classic',
    text:'Белый шкаф-купе в прихожей с зеркальной дверью и комодом.',
    photos:['ward-white-1'] },
  { id:'bath-mauve', title:'Ванная в пыльно-розовом', type:['bath'], style:'modern',
    text:'Рифлёные фасады, встроенный шкаф над инсталляцией, латунная сантехника.',
    photos:['bath-mauve-1','bath-mauve-2','bath-mauve-3'] },
  { id:'bath-beige', title:'Ванная с рифлёной тумбой', type:['bath'], style:'neo',
    text:'Тумба на ножках, круглое зеркало с рифлёной рамой, шкаф-пенал.',
    photos:['bath-beige-1','bath-beige-2'] },
  { id:'bath-grey', title:'Серая ванная с деревом', type:['bath'], style:'modern',
    text:'Подвесная тумба из шпона, шкаф-пенал, зеркало без рамы.',
    photos:['bath-grey-1'] },
  { id:'bath-black', title:'Чёрно-белая ванная', type:['bath'], style:'minimal',
    text:'Чёрная подвесная тумба, круглое зеркало, шкаф над инсталляцией.',
    photos:['bath-black-1','bath-black-2'] },
  { id:'bath-wood', title:'Тумба в ванной', type:['bath'], style:'modern',
    text:'Подвесная тумба из шпона с белой столешницей.',
    photos:['bath-wood-1'] }
];
